site_name: Model-based SLAM
nav: 
    - Home: 'README.md'
    - 'User Guide':
        - 'Get going': 'get_going.md'
    - 'Components':
        - 'GUI': 'gui.md'
        - 'SLAM': 'slam.md'
        - 'Sofa Viewer': 'sofa_viewer.md'
        - 'Feature Graph': 'feature_graph.md'
    - 'API Documentation':
        - 'EngineORB': 'api/orb.md'
        - 'Plotting with pyqtgraph': 'api/plotter.md'
        - 'Feature Graph': 'api/feature_graph.md'
repo_url: https://github.tik.uni-stuttgart.de/JHaag/Model_based_SLAM
edit_uri: edit/main/docs
site_author: Jonathan Haag
use_directory_urls : false
theme:
   name: readthedocs
   collapse_navigation : false
   prev_next_buttons_location: none
plugins:
    - mkdocstrings